---
name: Run All Tests

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.10

    - name: Create and activate venv
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Display Installed Dependencies
      run: python -m pip freeze

    - name: List Test Files
      run: ls tests

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*_test.py"

    - name: Run specific tests
      run: |
        python -m unittest tests/aoe_battlecry_test.py
        python -m unittest tests/board_test.py
        python -m unittest tests/card_class_test.py
        python -m unittest tests/card_import_test.py
        python -m unittest tests/deck_test.py
        python -m unittest tests/game_test.py
        python -m unittest tests/weapon_test.py

    - name: Run pre-commit
      run: pre-commit run --all-files
